# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SwiftCronExample' do
pod 'SwiftCron', :path => '../'
end

target 'SwiftCronExampleTests' do
pod 'SwiftCron', :path => '../'
end

