# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8.1
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
  - cd Example && pod install
  - set -o pipefail && xcodebuild test -workspace SwiftCronExample.xcworkspace -scheme SwiftCronExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' ONLY_ACTIVE_ARCH=YES | xcpretty
  - cd .. && pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
